---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - debug: msg="Starting deploy_cluster"

- import_playbook: init/main.yml

- import_playbook: openshift-node/private/bootstrap.yml

- import_playbook: common/private/control_plane.yml

- import_playbook: openshift-node/private/join.yml

- import_playbook: openshift-node/private/config.yml

- import_playbook: common/private/components.yml
